<?php
#CREAR BASES DE DATOS
#COMANDOS DESDE TERMINAL DOS:
#===============================0
# VIDEO 33
#=============
#CREATE DATABASE PRUEBA; CREA LA BASE DE DATOS
# ELIMINAR BASES DE DATOS
# DROP DATABASE PRUEBA ; ELIMINA LA BASE DEDATOS



